# Generated by Django 4.2.5 on 2023-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_productmodel_category_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('task', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Жалобы или поправки',
                'verbose_name_plural': 'Содержание жалобы',
            },
        ),
    ]
